local fake = require("spec.support.sources")

describe("Pricing: PriceService", function()
    local ns, Price

    before_each(function()
        ns = load_core({ login = true, money = 1 })
        Price = ns.Price
    end)

    it("walks the chain by priority and returns value and source", function()
        Price.RegisterSource(fake("tsm", 10, { market = { ["i:1"] = 500 } }))
        Price.RegisterSource(fake("auctionator", 20, { market = { ["i:1"] = 400, ["i:2"] = 300 } }))
        assert.same({ 500, "tsm" }, { Price.Get("i:1", "market") })
        assert.same({ 300, "auctionator" }, { Price.Get("i:2", "market") })
        assert.is_nil(Price.Get("i:3", "market"))
    end)

    it("puts the preferred source first for market and destroy", function()
        Price.RegisterSource(fake("tsm", 10, { market = { ["i:1"] = 500 } }))
        Price.RegisterSource(fake("auctionator", 20, { market = { ["i:1"] = 400 } }))
        Price.SetPreferred("auctionator")
        assert.same({ 400, "auctionator" }, { Price.Get("i:1", "market") })
        assert.equals("auctionator", GoblinomicsDB.settings.pricing.preferred)
    end)

    it("skips values <= 0 and isolates errors in sources", function()
        Price.RegisterSource(fake("broken", 1, { market = {} }, { Get = function() error("boom") end }))
        Price.RegisterSource(fake("zero", 2, { market = { ["i:1"] = 0 } }))
        Price.RegisterSource(fake("good", 3, { market = { ["i:1"] = 7 } }))
        assert.same({ 7, "good" }, { Price.Get("i:1", "market") })
        assert.equals(1, #WoWMock.errors)
    end)

    it("caches values and misses until invalidated", function()
        local src = fake("tsm", 10, { market = { ["i:1"] = 5 } })
        Price.RegisterSource(src)
        Price.Get("i:1", "market")
        Price.Get("i:1", "market")
        Price.Get("i:9", "market")
        Price.Get("i:9", "market")
        assert.equals(2, src.calls)
        Price.Invalidate("i:1")
        Price.Get("i:1", "market")
        assert.equals(3, src.calls)
        Price.Invalidate()
        Price.Get("i:9", "market")
        assert.equals(4, src.calls)
    end)

    it("emits PRICES_CHANGED once per burst of invalidations", function()
        local n = 0
        ns.Bus.On("PRICES_CHANGED", function() n = n + 1 end, "Spec")
        WoWMock.advance(1)
        n = 0
        Price.Invalidate("i:1")
        Price.Invalidate()
        WoWMock.advance(0.5)
        assert.equals(1, n)
    end)

    it("rejects invalid sources and unknown roles", function()
        assert.has_error(function() Price.RegisterSource({ id = "x" }) end)
        assert.is_nil(Price.Get("i:1", "nonsense"))
        assert.is_nil(Price.Get(nil, "market"))
    end)

    it("lists sources with status", function()
        Price.RegisterSource(fake("tsm", 10, { market = {} }, { Status = function() return { available = true, note = "n" } end }))
        local list = Price.Sources()
        assert.equals("tsm", list[1].id)
        assert.equals("n", list[1].note)
        assert.equals("vendor", list[#list].id)
    end)
end)
