-- M9: setup wizard - first start, steps, price sources, modules.
describe("UI: setup wizard", function()
    after_each(function() assert.same({}, WoWMock.errors) end)

    local fake = require("spec.support.sources")

    it("opens by itself 5 s after the first login of a fresh installation", function()
        local ns = load_core({ login = true })
        assert.is_true(ns.Setup.IsPending())
        assert.is_false(ns.Setup.IsShown())
        WoWMock.advance(6)
        assert.is_true(ns.Setup.IsShown())
        assert.equals(1, ns.Setup.state.step)
    end)

    it("waits for the end of combat", function()
        local ns = load_core({ boot = true })
        WoWMock.combat = true
        WoWMock.loggedIn = true
        WoWMock.fire("PLAYER_LOGIN")
        WoWMock.advance(6)
        assert.is_false(ns.Setup.IsShown())
        WoWMock.combat = false
        WoWMock.advance(11)
        assert.is_true(ns.Setup.IsShown())
    end)

    it("does not open for existing installations (schema 2 -> 3)", function()
        local ns = load_core({ login = true, db = { _schema = 2, settings = {} } })
        assert.is_false(ns.Setup.IsPending())
        WoWMock.advance(6)
        assert.is_false(ns.Setup.IsShown())
        assert.is_true(GoblinomicsDB.setup.done)
    end)

    it("walks the steps, skip and finish mark the setup as done", function()
        local ns = load_core({ login = true })
        ns.Setup.Show()
        local win = ns.Setup.window()
        win.next:GetScript("OnClick")(win.next, "LeftButton")
        assert.equals(2, ns.Setup.state.step)
        win.back:GetScript("OnClick")(win.back, "LeftButton")
        assert.equals(1, ns.Setup.state.step)
        win.skip:GetScript("OnClick")(win.skip, "LeftButton")
        assert.is_false(ns.Setup.IsShown())
        assert.is_true(GoblinomicsDB.setup.done)
        ns.EntryPoints.HandleSlash("setup")
        WoWMock.flush()
        assert.is_true(ns.Setup.IsShown())
        for _ = 1, 3 do win.next:GetScript("OnClick")(win.next, "LeftButton") end
        assert.equals(4, ns.Setup.state.step)
        assert.equals("Finish", win.next.label:GetText())
    end)

    it("reports the price sources: both, one or none", function()
        local ns = load_core({ login = true })
        local s = ns.Setup.PriceSources()
        assert.is_false(s.tsm.active or s.auctionator.active)
        ns.Price.RegisterSource(fake("auctionator", 20, { market = {} }))
        s = ns.Setup.PriceSources()
        assert.is_true(s.auctionator.active)
        assert.is_false(s.tsm.active)
        ns.Setup.Show()
        ns.Setup.Go(2)
        assert.equals("auctionator", ns.Price.Config().preferred)   -- the only active source is used
    end)

    it("switches modules in the modules step", function()
        local ns = load_gatherer()
        ns.Setup.Show()
        ns.Setup.Go(3)
        local page = ns.Setup.state.pages.modules
        assert.is_table(page)
        ns.Modules.SetEnabled("Goblinomics_Gatherer", false)
        ns.Setup.Go(4)
        ns.Setup.Go(3)
        assert.is_false(ns.Modules.IsEnabled("Goblinomics_Gatherer"))
    end)
end)
