describe("Core/Debug", function()
    it("is off by default and prints core events when switched on", function()
        local ns = load_core({ login = true })
        local m = ns.API.GetModule("Goblinomics_Debug")
        assert.equals("disabled", m.state)
        ns.EntryPoints.HandleSlash("debug on")
        assert.equals("enabled", m.state)
        assert.same({ enabled = true }, GoblinomicsDB.settings.modules.Goblinomics_Debug)
        WoWMock.set_money(100)
        WoWMock.fire("PLAYER_MONEY")
        WoWMock.set_money(250)
        WoWMock.fire("PLAYER_MONEY")
        local last = WoWMock.chat[#WoWMock.chat]
        assert.truthy(last:find("[MONEY]", 1, true))
        ns.EntryPoints.HandleSlash("debug off")
        assert.is_nil(GoblinomicsDB.settings.modules.Goblinomics_Debug)
        assert.is_false(ns.Bus.IsServiceActive("bags"))
    end)
end)
