local collect = require("spec.support.collect")

describe("Tracking: context", function()
    local ns, got

    before_each(function()
        ns = load_core({ login = true, money = 1 })
        got = collect(ns, { "CONTEXT_CHANGED" })
    end)

    it("maps interaction types by name", function()
        WoWMock.fire("PLAYER_INTERACTION_MANAGER_FRAME_SHOW", Enum.PlayerInteractionType.MailInfo)
        assert.is_true(ns.Context.IsOpen("mail"))
        assert.same({ key = "mail", active = true }, got.CONTEXT_CHANGED[1])
        WoWMock.fire("PLAYER_INTERACTION_MANAGER_FRAME_HIDE", Enum.PlayerInteractionType.MailInfo)
        assert.is_false(ns.Context.IsOpen("mail"))
        WoWMock.fire("PLAYER_INTERACTION_MANAGER_FRAME_SHOW", 9999)
        assert.equals(2, #got.CONTEXT_CHANGED)
    end)

    it("tracks trade, loot, craft and quest windows", function()
        WoWMock.fire("TRADE_SHOW")
        WoWMock.fire("LOOT_READY")
        WoWMock.fire("TRADE_SKILL_SHOW")
        WoWMock.fire("QUEST_COMPLETE")
        local s = ns.Context.Snapshot()
        assert.is_true(s.trade and s.loot and s.craft and s.quest)
        WoWMock.fire("LOOT_CLOSED")
        assert.is_nil(ns.Context.Snapshot().loot)
    end)

    it("keeps markers for their ttl without timers", function()
        local before = #WoWMock.timers
        ns.API.Context:Mark("repair", { cost = 5 }, 2)
        assert.same({ cost = 5 }, ns.API.Context().marks.repair)
        assert.equals(before, #WoWMock.timers)
        WoWMock.advance(3)
        assert.is_nil(ns.API.Context().marks)
    end)

    it("sets core markers for money loot and quest rewards", function()
        WoWMock.fire("CHAT_MSG_MONEY", "You loot 5 Copper")
        WoWMock.fire("QUEST_TURNED_IN", 1234, 100, 5000)
        local marks = ns.Context.Snapshot().marks
        assert.is_true(marks.lootMoney)
        assert.same({ questID = 1234, money = 5000 }, marks.questReward)
    end)

    it("labels a snapshot by priority", function()
        WoWMock.fire("LOOT_READY")
        WoWMock.fire("PLAYER_INTERACTION_MANAGER_FRAME_SHOW", Enum.PlayerInteractionType.Merchant)
        assert.equals("merchant", ns.Context.Label(ns.Context.Snapshot()))
    end)

    it("lists windows closed within the last 2 seconds as recent", function()
        WoWMock.fire("LOOT_READY")
        WoWMock.fire("LOOT_CLOSED")
        local s = ns.Context.Snapshot()
        assert.is_nil(s.loot)
        assert.is_true(s.recent.loot)
        WoWMock.advance(2.5)
        assert.is_nil(ns.Context.Snapshot().recent)
    end)
end)
